apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-service
  template:
    metadata:
      labels:
        app: fetch-service
    spec:
      containers:
      - name: fetch-service
        image: fetch-service:latest   # Käytetään paikallista kuvaa
        imagePullPolicy: Never        # ⚠️ Estetään kuvan lataus Docker Hubista
        ports:
        - containerPort: 50051
