apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-service
  template:
    metadata:
      labels:
        app: fetch-service
    spec:
      containers:
        - name: fetch-service
          image: fetch-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: ORTHANC_URL
              value: "http://orthanc:8042"
